version: '3.7'
services: 
  mysql-db-dev:
    image: mysql:8.0.16
    env_file: ../environment/dev.env
    expose: 
      - '3306'
    ports: 
      - 3306:3306
    restart: always
networks:
  default:
    name: dev_network
    driver: bridge
