version: '3.7'
services:
  user-service:
    image: nathantran/user-service-builder
    env_file: ../../environment/dev.env
    volumes:
      - ~/.m2:/root/.m2
      - ./:/app
    # entrypoint: [ "wait-for.sh", "mysql:3306" ]
    command: mvn spring-boot:run -Dspring-boot.run.profiles=dev --debug
    ports:
      - '8585:8080'
    external_links:
      - mysql-db-dev:mysql
networks:
  default:
    name: dev_network
    driver: bridge
